// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:915b4f52-b933-470f-b68d-0d92c0e33def',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'urtarget-hosting-mobilehub-1542430423',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd15bwbuqm8pwdh.cloudfront.net',
    'aws_mobile_analytics_app_id': '40ef9837a6e34ffe96b09676b516b0c9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8121813c-f533-4049-96de-167980e3ed08',
    'aws_project_name': 'UrTarget-2018-05-07-11-13-42',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'urtarget-mobilehub-1542430423',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_ncEzr9KPw',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '7sr4v3dvor3q65m6osuoa88fcn',
}

export default awsmobile;
