// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:ac3c26b4-8e22-41d0-88be-44209f67440a',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'urtarget-hosting-mobilehub-1557710018',
    'aws_content_delivery_bucket_region': 'us-west-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd3ux2diuk18y6h.cloudfront.net',
    'aws_mobile_analytics_app_id': 'b125fbdcd0ef43a891b3bef299760a40',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '0b9232b8-f09c-4f37-a5a4-d66bed468c63',
    'aws_project_name': 'UrTarget',
    'aws_project_region': 'us-west-2',
    'aws_resource_name_prefix': 'urtarget-mobilehub-1557710018',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-west-2_eUNJLSC4M',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5ccsrdertfh232igcmmt5s1c80',
}

export default awsmobile;
